# 라이브러리

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# 데이터 뽑아오는 함수

In [2]:
# 데이터 병합 및 year 열 추가 함수 정의의: SQL
def get_data_from_db(query):

    # mysql 접속 정보 정의
    username = "admin"
    password = "admin1234"
    host = "hk-toss-middle-project.cjkcuqkegqpx.eu-north-1.rds.amazonaws.com"
    database_name = "raw_data"

    # 데이터베이스 연결 문자열, connection string
    db_connection_str = f'mysql+pymysql://{username}:{password}@{host}/{database_name}'

    # 데이터 베이스 connector 얻어내기
    db_connection = create_engine(db_connection_str)
    db_connection

    df = pd.read_sql(query, con=db_connection)
    return df

# Transformer 정의

## 문자열 앞뒤 공백 제거 Transformer

In [4]:
# 앞뒤공백 제거 transformer
class StripTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, columns:list):
        # 입력한 columns가 문자열이면 리스트로 변환
        if isinstance(columns, str):
            self.columns = [columns]
        else:
            self.columns = columns

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        # 선택한 열 중에 데이터프레임에 실제로 존재하는 열만 선택
        columns_y = [col for col in self.columns if col in X.columns]

        # 선택한 열의 값들의 앞뒤 공백을 제거
        for col in columns_y:

            # 문자열 형식인지 확인
            if X[col].dtype == 'object':
                try:
                    X[col] = X[col].str.strip()
                except:
                    pass

        return X

## 열 탈락 / 열 이름 변경 Transformer

In [5]:
class RenameDropColumnsTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, rename_map:dict = {}, drop_columns:list = []):
        self.rename_map = rename_map
        # drop_columns가 문자열이면 리스트로 변환
        if isinstance(drop_columns, str):
            self.drop_columns = [drop_columns]
        else:
            self.drop_columns = drop_columns

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        # 실제로 데이터프레임에 존재하는 열만 drop
        self.drop_columns = [col for col in self.drop_columns if col in X.columns]
        # drop_columns가 존재하면 drop
        if self.drop_columns:
            X.drop(columns=self.drop_columns, inplace=True)

        # 실제로 데이터프레임에 존재하는 열만 선택
        rename_map = {key: value for key, value in self.rename_map.items() if key in X.columns}
        # rename_map이 존재하면 rename
        if self.rename_map:
            X.rename(columns=self.rename_map, inplace=True)
            
        return X

# PHI Table
- transform 내용 정리리리리리리리

## PHI Table 에만 필요한 Transformer
- 내용내용

In [6]:
class PHITableTransformer(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        # 단독 가구인 경우만 뽑기기
        X = X.loc[X["PHI_PID"].str.len() < 9, :]

        return X

## 3개년 병합해서 불러오기

In [10]:
query = f"""SELECT *, 2019 AS D_YEAR FROM raw_a_phi
            UNION ALL
            SELECT *, 2020 AS D_YEAR FROM raw_b_phi
            UNION ALL
            SELECT *, 2021 AS D_YEAR FROM raw_c_phi"""
phi = get_data_from_db(query)

## PHI Table 전처리 파이프라인

In [11]:
rename_map_phi = {'PHI_PID1' : 'PIDWON',
                  'PHI1' : 'PHI_Y',
                  'PHI2' : 'PHI_M',
                  'PHI3' : 'PHI_FORM',
                  'PHI4' : 'PHI_TYPE',
                  'PHI4_1_D' : 'PHI_TYPE_D',
                  'PHI4_2_D' : 'PHI_TYPE_C',
                  'PHI4_3_D' : 'PHI_TYPE_A',
                  'PHI4_4_D' : 'PHI_TYPE_N',
                  'PHI4_5_D' : 'PHI_TYPE_T',
                  'PHI4_6_D' : 'PHI_TYPE_AL',
                  'PHI4_7_D' : 'PHI_TYPE_M',
                  'PHI4_8_D' : 'PHI_TYPE_O',
                  'PHI5' : 'PHI_PREMIUM_YN',
                  'PHI6' : 'PHI_PREMIUM',
                  'PHR1' : 'PHI_CLAIM_YN',
                  'PHR2' : 'PHI_BENEFIT_YN',
                  'PHR3' : 'PHI_BENEFIT'}
drop_columns_phi = ['PHI_PID', 'PHI_PID2', 'PHI_PID3', 'PHI_PID4', 'PHI_PID5']
phi_pipeline = Pipeline([
    ('strip', StripTransformer(columns=['PHI_PID'])),
    ('phi_table', PHITableTransformer()),
    ('rename_drop', RenameDropColumnsTransformer(rename_map=rename_map_phi, drop_columns=drop_columns_phi))
])
phi_striped = phi_pipeline.fit_transform(phi)
phi_striped

C:\Users\user\AppData\Local\Temp\ipykernel_3876\2036449291.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop(columns=self.drop_columns, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_3876\2036449291.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.rename(columns=self.rename_map, inplace=True)

,HHID,PHI_N,PIDWON,PHI_Y,PHI_M,PHI_FORM,PHI_TYPE,PHI_TYPE_D,PHI_TYPE_C,PHI_TYPE_A,...,PHI_TYPE_T,PHI_TYPE_AL,PHI_TYPE_M,PHI_TYPE_O,PHI_PREMIUM_YN,PHI_PREMIUM,PHI_CLAIM_YN,PHI_BENEFIT_YN,PHI_BENEFIT,D_YEAR
0,112003011.0,101.0,11200301.0,2004.0,-9.0,3.0,"1,2,3,8",1.0,1.0,1.0,...,2.0,2.0,2.0,1.0,1.0,120000.0,1.0,1.0,60000.0,2019
1,112003011.0,102.0,11200302.0,2004.0,-9.0,3.0,"1,2,3,8",1.0,1.0,1.0,...,2.0,2.0,2.0,1.0,1.0,118000.0,2.0,NaN,NaN,2019
2,112010011.0,101.0,11201001.0,2015.0,3.0,2.0,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,48710.0,2.0,NaN,NaN,2019
3,112010011.0,102.0,11201001.0,2000.0,7.0,1.0,"1,2",1.0,1.0,2.0,...,2.0,2.0,2.0,2.0,3.0,62800.0,2.0,NaN,NaN,2019
4,112010011.0,103.0,11201002.0,2012.0,2.0,3.0,"1,2,3,8",1.0,1.0,1.0,...,2.0,2.0,2.0,1.0,1.0,201717.0,2.0,NaN,NaN,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64270,400007011.0,201.0,40000703.0,-9.0,-9.0,1.0,1,1.0,2.0,2.0,...,2.0,2.0,2.0,2.0,1.0,-9.0,2.0,NaN,NaN,2021
64271,400007011.0,202.0,40000704.0,-9.0,-9.0,1.0,1,1.0,2.0,2.0,...,2.0,2.0,2.0,2.0,1.0,-9.0,2.0,NaN,NaN,2021
64272,400008011.0,102.0,40000802.0,2014.0,12.0,3.0,"1,3",1.0,2.0,1.0,...,2.0,2.0,2.0,2.0,1.0,71740.0,1.0,1.0,506871.0,2021
64273,400008011.0,401.0,40000802.0,2018.0,5.0,1.0,2,2.0,1.0,2.0,...,2.0,2.0,2.0,2.0,1.0,21550.0,2.0,NaN,NaN,2021
64274,400008011.0,402.0,40000804.0,2011.0,2.0,3.0,"1,2,3",1.0,1.0,1.0,...,2.0,2.0,2.0,2.0,1.0,134560.0,2.0,NaN,NaN,2021

# IND Table

# MS Table